---
- name: Setup home dir with configurations and software
  hosts: all

  tasks:
    #- name: Copy config files to host
    #copy:
    #src: config.tar.gz
    #dest: ~/config.tar.gz
    #mode: 0600

    - name: Untar configuration files.
      unarchive:
        src: config.tar.gz
        dest: ~/

    - name: Create src directory
      file: path=~/src state=directory

    - name: Git repo for undercloud_containers
      git:
        repo: 'https://github.com/dprince/undercloud_containers.git'
        dest: ~/src/

    - name: Git repo for imain vimrc
      git:
        repo: 'https://github.com/imain/vimrc.git'
        dest: ~/src/

    - name: Git repo for tripleo-heat-templates
      git:
        repo: 'https://git.openstack.org/openstack/heat-templates'
        dest: ~/src/

